---
title: "NYC Schools Percepetion Survey"
author: "Cedric Vidonne"
output: html_notebook
---

**Guided Project: NYC Schools Perceptions**

Load needed packages for the analysis

```{r}
library(readr)
library(dplyr)
library(tidyr)
```

Load data sets into R

```{r}
combined <- read_csv("data/combined.csv")
survey <- read_tsv("data/masterfile11_gened_final.txt")
survey_d75 <- read_tsv("data/masterfile11_d75_final.txt")
```

Select needed data for analysis from Survey. Filter "High School" and select only aggregated data

```{r}
survey_select <- survey %>%
  filter(schooltype == "High School") %>%
  select(dbn:aca_tot_11)
```

Select needed data for analysis from Survey D75. Select only aggregated data

```{r}
survey_d75_select <- survey_d75 %>%
  select(dbn:aca_tot_11)
```

Rename dbn to DBN to match with combined df

```{r}
survey_combined <- survey_combined %>%
  rename(DBN = dbn)
```

Join combined and combined_surveys

```{r}
combined_all <- combined %>%
  left_join(survey_combined, by = "DBN")
```

